### ISSUE TITLE
When I take car out, I can still spawn it infinitely times 

### ISSUE THREAD

**Issue by ThatGuyJacobee** [lilfuchs/esx_drp_garage#19]
Once I spawn a car it doesn't become unavailable and so I can spawn it over and over again without it saying it's out of the garage. So I get a long error: 

[ERROR] [MySQL] [esx_eden_garage] An error happens on MySQL for query "[object Object]": ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'
Error: (node:608) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
    at process.<anonymous> (internal/process/promises.js:27:25)
    at <anonymous>
    at Query.db.query [as _callback] (mysql-async.js:4973:13)
    at Query.Sequence.end (mysql-async.js:280:24)
    at Query.ErrorPacket (mysql-async.js:2122:8)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
Error: (node:608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: (node:608) UnhandledPromiseRejectionWarning: Error: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'
    at Query.Sequence._packetToError (mysql-async.js:244:14)
    at Query.ErrorPacket (mysql-async.js:2109:18)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (mysql-async.js:4728:23)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4985:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by OhTanoshi** [comment]
Check and see if the latest commit in stable release fixes anything

**Comment by OhTanoshi** [comment]
If this isn't fixed in the latest commit then ill look into it when my server comes in the mail. Since i will then be coming back to fivem and i will most likely release a c# version.

**Comment by DrDrProfessor1305** [comment]
It maybe the SQl if you didnt import correctly
